### ISSUE TITLE
when will release ImageNet pretrain model?

### ISSUE THREAD

**Issue by L1aoXingyu** [DingXiaoH/ACNet#11]

**Comment by csliuchang** [comment]
me too, the vgg pretrain model train on imagenet i need.

**Comment by anti1990** [comment]
Please share the pre-training parameters of resnet on imagenet

**Comment by bixiaopeng0** [comment]
yeah,me too

**Comment by DingXiaoH** [comment]
Sorry, I am pretty busy working for my NeurIPS submission these days. The codes and weights will be released later.

**Comment by F1sh-Yu** [comment]
need it very much

**Comment by mlkk518** [comment]
Wait for it's coming.  Thanks a lot!

**Comment by Totoro-wen** [comment]
I can't find the ImageNet pretrain model
