### ISSUE TITLE
Is the difference from the original paper only in the learning rate?

### ISSUE THREAD

**Issue by pjtmdpj223** [DingXiaoH/ACNet#19]
The result here is 94.31 with resnet-56 for cifar-10, but in the original resnet paper from He, the result is 93.03.
Is the difference only in the learning rate?

**Comment by yangyanli** [comment]
In this repo, all the 50K samples from the train split are used for training, while in the original resnet paper, 45K are used for training (the last 5K are used for validation).

I think this probably is the major contribution to the difference on the testing error.
