### ISSUE TITLE
about the parameter innitialization of BatchNorm

### ISSUE THREAD

**Issue by zcc1019** [DingXiaoH/ACNet#27]
I am a new learner of Deeplearning.I Confused by some code. 
![image](https://user-images.githubusercontent.com/63686187/89045887-d7ea0680-d37e-11ea-8ae5-ec34d626fa64.png)
in  your  acnet.abc.py. what the meaning of reduce_gama and gamma_int.  they seem to be two defferent innitialization method. when is the proper time  or  occation to do innitialization for each 
innitialization method? and why the choice of the use_last_bn must be different from the choice  of reduce_gama, what the accosiation between two viarables.
I am trying to  understand the code and applying in my own code. Thank your for your sharing and attention

**Comment by DingXiaoH** [comment]
They are just variants I once tried in my experiments. Maybe they would work better in some cases.
The default arguments are the configurations reported in the paper (not use_last_bn and gamma_init = 1).
