### ISSUE TITLE
train loss and accuracy curve for single gpu

### ISSUE THREAD

**Issue by zcc1019** [DingXiaoH/ACNet#28]
in the programme named ndp_train.py. When I try to draw a train loss curve and accuracy curve with a single gpu(the network just contains 6 layers).I realize that the prerequisites(if iteration % cfg.tb_iter_period == 0 and engine.world_rank == 0) I can not achieve. because you have set the engine.world_rank == 1 when training a net with a single gpu( self.world_size = 1,self.world_rank = 
,self.devices = [0]). I am very confused.  if training loss in a single gpu should not draw a related curve as a criterion

**Comment by DingXiaoH** [comment]
Thank you for pointing out this bug. Fixed:
in engine.py, the single-gpu case:
self.world_rank = 1  --->  self.world_rank = 0
