### ISSUE TITLE
this work is great, but can you give a example how we can replace 3*3 conv by using 3*3+1*3+3*1

### ISSUE THREAD

**Issue by nankeermeng** [DingXiaoH/ACNet#3]

**Comment by DingXiaoH** [comment]
Thank you for your interest in this paper. Please check class ACBlock in acnet/acnet_builder.py.

**Comment by feidasheng** [comment]
![image](https://user-images.githubusercontent.com/44360716/68918232-4e6eb600-07a8-11ea-9994-6ebf8598f431.png)
hello,I will insert your ACBlock class, why is there a padding error, I want to hear your thoughts?

**Comment by DingXiaoH** [comment]
Thank you for pointing this out. I fixed it several minutes ago. Negative padding means cropping, but I forgot to deal with such cases. Please check the latest version of acnet_builder.
