### ISSUE TITLE
请问如何应用到resnet里？

### ISSUE THREAD

**Issue by ZangHuanyu** [DingXiaoH/ACNet#30]
@DingXiaoH @ShawnDing1994 作者你好，请问怎么将ACNet应用到ResNet里，需要用到哪些files？问题有些基础，先谢谢回复了！

**Comment by DingXiaoH** [comment]
下面这条命令可以重复将ACNet用到ResNet里的实验，请阅读相关代码：
python acnet/do_acnet.py -a src56 -b acb

**Comment by ZangHuanyu** [comment]
> 下面这条命令可以重复将ACNet用到ResNet里的实验，请阅读相关代码：
> python acnet/do_acnet.py -a src56 -b acb

报错了，没有module_map, 我确实也没有找到在哪里

**Comment by DingXiaoH** [comment]
哪里会报这个错？
train_main里面用到了model_map，没有module_map吧

**Comment by ZangHuanyu** [comment]
> 哪里会报这个错？
> train_main里面用到了model_map，没有module_map吧

就是运行do_acnet.py这个的时候，直接报错

**Comment by DingXiaoH** [comment]
试过README里面描述的下面这一步吗
export PYTHONPATH=.

**Comment by ZangHuanyu** [comment]
> 试过README里面描述的下面这一步吗
> export PYTHONPATH=.

实在抱歉，我用的是windows，不知道这些指令应该在哪里执行，怎么执行
ln -s YOUR_PATH_TO_CIFAR cifar10_data
所以我是直接在pycharm里运行的do_acnet.py，然后报错的

**Comment by DingXiaoH** [comment]
那我觉得这个repo不适合作为练习python的材料……

**Comment by ZangHuanyu** [comment]
> 那我觉得这个repo不适合作为练习python的材料……

实在感谢博主的耐心回复了…我自己再研究下好了

**Comment by leayz-888** [comment]
请问作者可以将ACNet应用到ResNeXt中吗？  该怎么用呢？期待你的回答
