### ISSUE TITLE
Does the val loss match the real performance of the inference model?

### ISSUE THREAD

**Issue by SingL3** [DingXiaoH/ACNet#32]
Hi, I am trying to ensemble your work into my detection network,
And I have some confusion about the process of validation. During inference, the network would be modified to merge the kernel, but it seems that the network remain the same as training in the process of validation during training.
I am wondering whether the val loss could actually match the real performance with the inference model.
I will appreciate it if someone reply, thank you!

**Comment by DingXiaoH** [comment]
Hi, I don't really understand your question. I assume it is like
Model A: the val-during-train model. You have simply called model.eval() (if you are using pytorch) and will call model.train() after validation to continue training.
Model B: the actually-converted model. You do this only after training and before deployment.
I am really confident that model A and B will produce identical outputs.

**Comment by SingL3** [comment]
Yeah! That is what i am wondering. Thank you!
Now I am trying to test my trained model. I am not using your pipeline to convert the model like this:
1. train a network and output its parameter
2. read the parameter throught h5df
3. convert the parameter
4. output the converted parameter through h5df
5. read the converted model and testing.
I am doing so like this:
1. train a network and output its parameter
2. load the parameter using torch.load()
3. convert the paramter
4. load the converted parameter using self.load_state_dict() without outputing it to a new .pth
And I got this error:
```
ACNet/acnet/acnet_fusion.py", line 11, in _fuse_kernel
    return kernel * b_gamma / b_std
TypeError: mul(): argument 'other' (position 1) must be Tensor, not numpy.ndarray
```
and I add
```
kernel = kernel.numpy()
```
And I got this:
```
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in _load_from_state_dict
    param.copy_(input_param)
TypeError: copy_(): argument 'other' (position 1) must be Tensor, not numpy.ndarray
```
I am not sure if this is a bug.
