### ISSUE TITLE
Error in ACBuilder

### ISSUE THREAD

**Issue by ZangHuanyu** [DingXiaoH/ACNet#33]
@DingXiaoH 
我想测一下作者的resnet，但是得到了以下报错，请问是怎么回事？

self.conv1 = builder.Conv2dBNReLU(3, int(64 * width_multiplier), kernel_size=3, stride=1, padding=1)
TypeError: Conv2dBNReLU() missing 1 required positional argument: 'out_channels'

**Comment by ZangHuanyu** [comment]
我觉得可能是width_multiplier参数的问题，我直接赋的None。
另外想问一下cfg.deps是什么参数，没找到在哪个文件

**Comment by DingXiaoH** [comment]
请问您使用时运行的命令是？

**Comment by ZangHuanyu** [comment]
> 请问您使用时运行的命令是？

我是直接在自己的main文件里import了create_ResNet18和create_ResNet34，然后run以后显示的报错。
因为没有找到cfg是什么，所以在acnet_builder里删掉了base_config这个参数，main文件里面是net = Resnet18(ACNetBuilder) or net = Resnet34(ACNetBuilder)

**Comment by DingXiaoH** [comment]
这一整套代码的设计目标是复现实验和保证跟baseline一样的架构。如果你要用到自己的模型里的话，我建议直接用ACBlock这个类替换你原本的 conv-BN

**Comment by ZangHuanyu** [comment]
> 这一整套代码的设计目标是复现实验和保证跟baseline一样的架构。如果你要用到自己的模型里的话，我建议直接用ACBlock这个类替换你原本的 conv-BN

原来如此，我确实用的是一个图像识别其他数据集，是用AC block代替initial resnet里面所有的3*3+BN是吗
