### ISSUE TITLE
绘制曲线

### ISSUE THREAD

**Issue by ZangHuanyu** [DingXiaoH/ACNet#34]
@DingXiaoH @ShawnDing1994 
请问作者，论文里面figure5的图是怎么画的，想学习一下。是怎么画出带不同颜色的阴影的对应曲线的？谢谢

**Comment by DingXiaoH** [comment]
matplotlib.pyplot 有一个fill函数 可以在两条曲线之间填上颜色
所以画这个的步骤是：
1. 画出(x, mean)这条线
1. fill(x, mean - std, mean + std) （具体的名字和参数形式我忘了）



dxh17@mails.tsinghua.edu.cn
 
发件人： ZangHuanyu
发送时间： 2020-11-18 23:19
收件人： DingXiaoH/ACNet
抄送： DingXiaoH; Mention
主题： [DingXiaoH/ACNet] 绘制曲线 (#34)
@DingXiaoH @ShawnDing1994
请问作者，论文里面figure5的图是怎么画的，想学习一下。是怎么画出带不同颜色的阴影的对应曲线的？谢谢
