### ISSUE TITLE
About BN layer

### ISSUE THREAD

**Issue by HCookY95** [DingXiaoH/ACNet#35]
@ShawnDing1994 @DingXiaoH 
Hi friend,

That's a pretty impressive work. 

I wanna put the AC block into my own network, it's a ResNet-like architecture. I have noticed there is BN layer after each kernel (square, horizontal and vertical), and then add those three together to get the result of AC block.

So I have questions, do I still need add one more BN layer after the result? eg. When define ResNet, does it still need to add a BN layer in bottleneck?

**Comment by DingXiaoH** [comment]
There is no need to put a BN after an ACB.
E.g., the bottleneck of ResNet-50 should be like
1x1conv - BN - ReLU - ACB - ReLU - 1x1conv - BN
