### ISSUE TITLE
depth conv的实验

### ISSUE THREAD

**Issue by pawopawo** [DingXiaoH/ACNet#39]
请问使用depth conv的mobilenet支持这种权重融合吗

**Comment by ShawnDing1994** [comment]
支持的。
groups 可以是任意的。repvgg.py里有相关的代码

input_dim = self.in_channels // self.groups
kernel_value = np.zeros((self.in_channels, input_dim, 3, 3), dtype=np.float32)
for i in range(self.in_channels):
    kernel_value[i, i % input_dim, 1, 1] = 1



shawnding@outlook.com
 
发件人： pawopawo
发送时间： 2021-01-14 15:34
收件人： DingXiaoH/ACNet
抄送： Subscribed
主题： [DingXiaoH/ACNet] depth conv的实验 (#39)
请问使用depth conv的mobilenet支持这种权重融合吗

**Comment by ShawnDing1994** [comment]
不好意思 刚才发错了 我以为是另一个repo的



shawnding@outlook.com
 
发件人： pawopawo
发送时间： 2021-01-14 15:34
收件人： DingXiaoH/ACNet
抄送： Subscribed
主题： [DingXiaoH/ACNet] depth conv的实验 (#39)
请问使用depth conv的mobilenet支持这种权重融合吗

**Comment by ShawnDing1994** [comment]
ACNet也是支持depth conv的。ACBlock里的groups可以是任意的。



shawnding@outlook.com
 
发件人： pawopawo
发送时间： 2021-01-14 15:34
收件人： DingXiaoH/ACNet
抄送： Subscribed
主题： [DingXiaoH/ACNet] depth conv的实验 (#39)
请问使用depth conv的mobilenet支持这种权重融合吗

**Comment by pawopawo** [comment]
谢谢你的回复～
如果是mobilenetv2 这种含较多1*1conv的网络，是不是1*1conv就不能做re-param了，repvgg或acnet还能有较大的收益吗？

**Comment by ShawnDing1994** [comment]
对，1x1没法用1x3或3x1 reparam。这是因为前者的感受野小于后者。但是1x1上可以加identity。



shawnding@outlook.com
 
发件人： pawopawo
发送时间： 2021-01-15 13:58
收件人： DingXiaoH/ACNet
抄送： Ding Xiaohan; Comment
主题： Re: [DingXiaoH/ACNet] depth conv的实验 (#39)
谢谢你的回复～
如果是mobilenetv2 这种含较多11conv的网络，是不是11conv就不能做re-param了，repvgg或acnet还能有较大的收益吗？
