### ISSUE TITLE
关于ACblock ，border的卷积核构建

### ISSUE THREAD

**Issue by DDxk369** [DingXiaoH/ACNet#42]
大神您好，这里想问下关于ACNet论文中图6.(c)中的边缘卷积核骨架有开源的构建方式么？自己没有找到

**Comment by DingXiaoH** [comment]
只要使用手动padding（torch.nn.functional.pad），上下左右pad的不一样就可以了。
注意使用手动padding的时候，nn.Conv2d要设定padding=0
