### ISSUE TITLE
关于ACBlock部分逻辑的疑问

### ISSUE THREAD

**Issue by njustBShen** [DingXiaoH/ACNet#45]
您好，拜读您的论文及开源代码后，有一些疑问想向您咨询。
# acb.py Line21
center_offset_from_origin_border = padding - kernel_size // 2
上述语句是在计算什么，能否简单阐述一下
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
# acb.py Line24~Line33
if center_offset_from_origin_border >= 0:
   ……
else:
  ……
这里面的两个分支分别代表什么？if分支比较好理解，一些通常的设定例如p=1，k=3均会进入该分支，但是else分支对应哪些具体的情况？
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
# acb.py Line29~Line33
else:
    self.ver_conv_crop_layer = CropLayer(crop_set=ver_pad_or_crop)
    ver_conv_padding = (0, 0)
    self.hor_conv_crop_layer = CropLayer(crop_set=hor_pad_or_crop)
    hor_conv_padding = (0, 0)

若进入else分支，则center_offset_from_origin_border<0,该分支下执行对输入图的crop操作，
#crop_layer.py
class CropLayer(nn.Module):

  #   E.g., (-1, 0) means this layer should crop the first and last rows of the feature map. And (0, -1) crops the first and last columns
  def __init__(self, crop_set):
      super(CropLayer, self).__init__()
      self.rows_to_crop = - crop_set[0]
      self.cols_to_crop = - crop_set[1]
      assert self.rows_to_crop >= 0
      assert self.cols_to_crop >= 0

  def forward(self, input):
      if self.rows_to_crop == 0 and self.cols_to_crop == 0:
          return input
      elif self.rows_to_crop > 0 and self.cols_to_crop == 0:
          return input[:, :, self.rows_to_crop:-self.rows_to_crop, :]
      elif self.rows_to_crop == 0 and self.cols_to_crop > 0:
          return input[:, :, :, self.cols_to_crop:-self.cols_to_crop]
      else:
          return input[:, :, self.rows_to_crop:-self.rows_to_crop, self.cols_to_crop:-self.cols_to_crop]

显然一旦进入else分支，以crop_set=ver_pad_or_crop为例，crop_set=(padding, center_offset_from_origin_border)，即crop_set[1]<0,即 self.cols_to_crop = - crop_set[1]>0,永远不可能出现self.cols_to_crop == 0的情况，为何forward中仍出现相关的判断情况。

此外，若p=1,k=5,显然也是进入else分支的，此时crop_set=ver_pad_or_crop=（1，-1）
那么self.rows_to_crop = - crop_set[0]=-1，由语句assert self.rows_to_crop >= 0触发报错，显然，只要进入else分支时p不等于0均会产生该问题，很让人困惑。

既然明确了
assert self.rows_to_crop >= 0
assert self.cols_to_crop >= 0

为什么在forward中仍然要下面这种判断情况，我认为由上面的断言存在，不可能会有机会进入这个分支
else:
      return input[:, :, self.rows_to_crop:-self.rows_to_crop, self.cols_to_crop:-self.cols_to_crop]
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
希望您能在百忙中回复，感谢！

**Comment by DingXiaoH** [comment]
您好，这些只是为了处理padding而已，都是细枝末节，我觉得完全不重要。
只要理解了论文中的Figure 2，这些都是非常自然的东西。
这些逻辑里也许有不重要、不简洁、冗余的地方，但我也没有必要花时间去思考和重构。因为我觉得我没有必要把这些代码写的很完美，我没有这么多时间。
