### ISSUE TITLE
Good work but more analysis of acnet could be done

### ISSUE THREAD

**Issue by xw324** [DingXiaoH/ACNet#5]
I think this is some interesting work. In theory, it feels like the 1x3 and 3x1 kernels essentially just increase the augment the gradient of the skeleton entries compared to a single 3x3 kernel.

Another difference is then the initialization. 

ACnet should also converge faster than standard nets, since now we are doing multiple weight initialization for skeleton entries, it has a better chance to produce a weight that is closer to a local minimum. 

This perhaps helps with escaping local saddle points as well, since now the optimizer can descend from multiple angles for the skeleton entries. 

I think at least another paper for a much better analysis on the theory side can be done :)

**Comment by DingXiaoH** [comment]
Thank you for the insights! Maybe we can co-author!
